upstream app_server {
    server flask:5000;
}


server {
    listen 80;
    server_name banana-code-kids.fvds.ru;

    ssl_certificate /certs/banana-code-kids.fvds.ru.crt;
    ssl_certificate_key /certs/banana-code-kids.fvds.ru.key;

    location / {
        proxy_pass http://app_server;
    }
}



server {
    listen 443 ssl;
    server_name banana-code-kids.fvds.ru;

    # Path to your SSL certificate and key
    ssl_certificate /certs/banana-code-kids.fvds.ru.crt;
    ssl_certificate_key /certs/banana-code-kids.fvds.ru.key;

    # Recommended SSL settings
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_ciphers HIGH:!aNULL:!MD5;
    if ($host != 'banana-code-kids.fvds.ru') {
           return 444;
       }
    # Proxy settings
    location / {
        proxy_pass http://app_server;  # flask
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Optional: Serve static files
    #location /web/ {
        #alias /web/;
    #}
}
